<?php

/*
  Description: Block which shows featured image
*/

class SoliFeaturedImageBlock {
  function __construct() {
    add_action('init', array($this, 'adminAssets'));
  }

  /**
   * Reads the script dependencies and version generated by wp-scripts for a
   * build entry point.
   *
   * The generated *.asset.php files are the only reliable source for these:
   * hard coding the handles silently breaks the bundles whenever webpack
   * externalises something new (for example `react-jsx-runtime`).
   *
   * @param string $entry     Build entry point name, e.g. `index`.
   * @param array  $fallback  Dependencies to use when the build is missing.
   * @return array{dependencies: string[], version: string}
   */
  private function assetMeta($entry, $fallback = array()) {
    $asset_file = plugin_dir_path(__FILE__) . 'build/' . $entry . '.asset.php';

    if (file_exists($asset_file)) {
      $asset = include $asset_file;

      if (is_array($asset) && isset($asset['dependencies'])) {
        return array(
          'dependencies' => $asset['dependencies'],
          'version' => isset($asset['version']) ? $asset['version'] : SOLI_FEATURED_IMAGE__PLUGIN_VERSION,
        );
      }
    }

    return array(
      'dependencies' => $fallback,
      'version' => SOLI_FEATURED_IMAGE__PLUGIN_VERSION,
    );
  }

  function adminAssets() {
    $editor_asset = $this->assetMeta('index', array('wp-blocks', 'wp-element', 'wp-editor', 'wp-api-fetch'));

    wp_register_style('block-featured-image-css', plugin_dir_url(__FILE__) . 'build/index.css', array(), SOLI_FEATURED_IMAGE__PLUGIN_VERSION);
    wp_register_script(
      'block-featured-image-js',
      plugin_dir_url(__FILE__) . 'build/index.js',
      array_merge(array('wp-blocks'), $editor_asset['dependencies']),
      $editor_asset['version']
    );
    register_block_type('soli/featured-image', array(
      'editor_script' => 'block-featured-image-js',
      'editor_style' => 'block-featured-image-css',
      'render_callback' => array($this, 'theHTML'),
    ));
  }

  /**
   * The block is an editor-side tool: it sets the post's featured image and
   * orchestra categories. It deliberately renders nothing on the front end.
   */
  function theHTML($attributes, $content, $block) {
    return '';
  }
}

$soliBlockIssueTracker = new SoliFeaturedImageBlock();

function soli_featured_image_modify_post_type_args($args, $post_type) {
  if ('post' === $post_type || 'page' === $post_type) {
    $args['template'] = array(
      array('soli/featured-image', array(
        'lock' => array(
          'move' => true,
          'remove' => true
        )
      )),
    );
  }
  return $args;
}

add_filter('register_post_type_args', 'soli_featured_image_modify_post_type_args', 10, 2);
